<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZUzoxoc\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZUzoxoc/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZUzoxoc.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZUzoxoc\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZUzoxoc\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ZUzoxoc',
    'container.build_id' => 'adf4d57e',
    'container.build_time' => 1550499431,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZUzoxoc');
